openapi: 3.0.3
info:
  title: SDN Controller API
  version: "1.0.0"
servers:
  - url: http://{controller}:{port}/api/v1
    variables:
      controller: { default: 127.0.0.1 }
      port: { default: "8080" }
paths:
  /health:
    get:
      summary: Liveness
      responses: { "200": { description: OK } }
  /stats/ports:
    get:
      summary: Port stats
      responses: { "200": { description: OK } }
  /stats/flows:
    get:
      summary: Flow stats
      responses: { "200": { description: OK } }
  /topology/nodes:
    get:
      summary: Switches
      responses: { "200": { description: OK } }
  /topology/links:
    get:
      summary: Directed links
      responses: { "200": { description: OK } }
  /hosts:
    get:
      summary: Learned hosts
      responses: { "200": { description: OK } }
  /paths:
    get:
      summary: Candidate paths
      parameters:
        - in: query
          name: src_mac
          required: true
          schema: { type: string }
        - in: query
          name: dst_mac
          required: true
          schema: { type: string }
        - in: query
          name: k
          required: false
          schema: { type: integer, default: 2 }
      responses:
        "200": { description: OK }
        "404": { description: Hosts not learned }
  /actions/route:
    post:
      summary: Install route (both directions)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - required: [src_mac, dst_mac, path_id]
                  properties:
                    src_mac: { type: string }
                    dst_mac: { type: string }
                    path_id: { type: integer, minimum: 0 }
                    k: { type: integer, minimum: 1, default: 2 }
                - required: [src_mac, dst_mac, path]
                  properties:
                    src_mac: { type: string }
                    dst_mac: { type: string }
                    path: { type: array, items: { type: integer } }
      responses:
        "200": { description: Applied }
        "400": { description: Validation error }
        "404": { description: Hosts not learned }
        "429": { description: Cooldown active }
    delete:
      summary: Delete flows for host pair
      parameters:
        - in: query
          name: src_mac
          required: true
          schema: { type: string }
        - in: query
          name: dst_mac
          required: true
          schema: { type: string }
      responses:
        "200": { description: Deleted }
        "404": { description: Not found }
  /actions/list:
    get:
      summary: List installed routes
      responses: { "200": { description: OK } }
  /metrics/links:
    get:
      summary: Derived per-link tx_bps
      responses: { "200": { description: OK } }
